erp:
  devMode: false

server:
  port: 80

spring:
  datasource:
    druid:
      url: jdbc:mysql://10.0.16.13:3306/erp?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true #url
      username: erp  #用户名
      password: UVGsg5TNGFfJZVuA  #密码
jwt:
  config:
    key: 49c089f061d4d546f259a14b49c35249
    ttl: 604800000 # 7天
